### ISSUE TITLE
Glossary: Jump to entry anchor

### ISSUE THREAD

**Issue by balcse** [micado-eu/migrant_application#149]
In the glossary, if you open an existing entry (or go there from a link) which is further below, the app scrolls up to the top automatically. So the user has to scroll down again to get to the entry they want to see. Is it possible to add a text anchor and jump right there?

**Comment by ivchicano** [comment]
Fixed https://github.com/micado-eu/migrant_application/commit/e2e630e037cf83a4bba04780c5f3499b233a4ea5

**Comment by balcse** [comment]
it still does not work. when you minimize the window and open a glossary term from further down, it still jumps to the top

**Comment by ivchicano** [comment]
Fixed by https://github.com/micado-eu/migrant_application/commit/a1a0cbc6ca2093000003e6513ade0ed14bc86293 (hopefully)

**Comment by balcse** [comment]
sorry, it is still not working

**Comment by balcse** [comment]
![glossary](https://user-images.githubusercontent.com/15378003/119473878-e3fae680-bd4b-11eb-9044-29e17ecb6d7d.gif)


Here you can see, if I open "residence permit", it jumps back to the top and I have to scroll down again

**Comment by ivchicano** [comment]
Have you cleared the cache? It seems to work normally for me.

**Comment by balcse** [comment]
Yes, that was the problem. Now it works. Thanks for fixing it! :)
